### ISSUE TITLE
Design the user details dashboard

### ISSUE THREAD

**Issue by blockrideNFT** [BlockrideNFT-org/BlockrideHackathonApp#4]
# Dashboard: User details:
### Build the user details dashboard using typescript

![Dashboard: User details](https://github.com/BlockrideNFT-org/BlockrideHackathonApp/assets/110558156/756aec4f-32df-4b71-99ed-974d8e4d4af5)

Front end lead: @horlard 
Useful Links:
[Figma file](https://www.figma.com/file/DWewLyeJ6oulQ4UFxv324H/Blockride?type=design&node-id=15%3A6&mode=design&t=Ha41HdFeo1amgh2x-1)
[Website](https://blockride-hackathon-app.vercel.app/)

**Comment by KitanGarcia** [comment]
Hey @blockrideNFT @horlard !

I saw this project looking to build for Hyperdrive and thought it sounded super interesting! I'd love to lend a hand if you're up for it.

I went ahead and forked the repo and coded up the dashboard from the above image; you can see it here: https://github.com/KitanGarcia/BlockrideHackathonApp/tree/dashboard

I want to note a few things here, just to clarify:
1. This is a bit of a rough draft, as I did not have access to the Figma file. I got the colors by sampling with an eyedropper. If given access, I'm happy to make some tweaks to the styling and get it exactly right.
2. Since not all the images were in the repo (ie. green arrow for claimable rewards, SOL icon, company logos), I just left a placeholder image, in this case the grey Solana svg.
3. I noticed you use CSS to create a styled Container div. I was a little confused by this since Tailwind is also used in the project. Is there a reason both forms of styling are used? I just stuck to Tailwind, but can try to learn and adhere to your conventions.
4. I didn't really explore making it mobile friendly and taking other viewports into account yet.

If you like what you see and are interested in working together, I'm happy to address all of the above to clean things up to your standards, and would love some feedback!
Thanks!
